import { DidacticSequence } from "./types";

export const preloadedExamples: { label: string; sequence: DidacticSequence }[] = [
  {
    label: "Ejemplo 1: Agenda de la clase (Nivel 1a / Elemental)",
    sequence: {
      title: "Hacer la agenda de contactos de la clase",
      targetLevel: "Nivel 1a (Elemental 1a)",
      targetGroupDescription: "Estudiantes de nivel inicial absoluto (A1), jóvenes y adultos recién llegados a Buenos Aires para realizar estudios universitarios o turismo largo. Tienen la necesidad inmediata de socializar con sus nuevos compañeros de aula.",
      objectives: "Que los estudiantes sean capaces de: \n1. Saludar formal e informalmente e identificarse en contextos de grupo.\n2. Preguntar y dar datos personales básicos (nombre, número de teléfono, correo electrónico).\n3. Deletrear nombres y apellidos y solicitar aclaración o repetición cuando no comprendan.\n4. Reconocer la organización alfabética de directorios.",
      contents: "- Gramática: Verbos Ser (soy, eres, es), Llamarse (me llamo, te llamas), Tener (tengo, tienes, tiene). Adjetivos posesivos. Preguntas con ¿Cómo?, ¿Cuál?, ¿Tienes...?. Escritura y fonética elemental (b vs v, jota, diptongos).\n- Léxico: El abecedario en español, números del 0 al 9, léxico de telecomunicaciones (arroba, punto, prefijo, móvil, fijo).\n- Cultura: Costumbres sobre el uso de doble apellido en el ámbito hispanohablante y los apodos comunes.",
      inputs: "- Diálogo grabado y escrito entre Alicia (Martín) y Sergio (Navarro), donde se presentan, se piden el celular, deletrean sus correos alternativos (con b, v, g, y @) y aclaran sonidos complejos del español.\n- Lista desordenada de nombres internacionales y números ficticios.",
      enablingTasks: "Paso 1: Dinámica de activación de saberes previos: reflexionar sobre cómo saludamos en nuestro país y cómo se preguntará en español comercial u informal.\nPaso 2: Comprensión auditiva: los alumnos escuchan el diálogo de Alicia y Sergio, completando los huecos de la transcripción escrita con los nombres, apellidos y teléfonos correspondientes.\nPaso 3: Foco formal (Abecedario y letras): los estudiantes repasan el alfabeto hispánico, diferenciando la fonética de la 'c', 'g', 'j', 'z', 'rr' y 'll'. Practican deletreando sus propios nombres con su compañero de banco.\nPaso 4: Ejercitación de números por turnos: Un estudiante lee un número celular de la ficha de práctica y el compañero busca el nombre de pila asociado.\nPaso 5: Mecanismos de reparación: Aprender entonaciones de control ('¿Sergio qué?', '¿Deletreás por favor?').",
      finalTask: "La Tarea Final consiste en realizar una ronda de entrevistas directas a todos los compañeros del curso para pedirles sus nombres completos, teléfonos y correos. Posteriormente, cada estudiante armará su propia agenda escrita de contactos de la clase, ordenando todos los contactos alfabéticamente por su primer apellido, siguiendo la convención cultural hispana negociada previamente."
    }
  },
  {
    label: "Ejemplo 2: Preparar un postre - Tiramisú (Nivel 2 / Elemental 2)",
    sequence: {
      title: "Descubrimos la pastelería: Elaboramos y evaluamos una receta",
      targetLevel: "Nivel 2 (Elemental 2)",
      targetGroupDescription: "Estudiantes universitarios intermedios-bajos (A2), interesados en gastronomía y costumbres culinarias de Latinoamérica y España, con fines de socialización y recreación.",
      objectives: "Que los estudiantes sean capaces de:\n1. Comprender e interpretar recetas de cocina e instrucciones paso a paso.\n2. Dar instrucciones directas e impersonales para realizar una preparación gastronómica.\n3. Expresar valoraciones de gusto, sabor, textura y dificultad.\n4. Justificar elecciones gastronómicas de manera sencilla.",
      contents: "- Gramática: Formas de dar instrucciones: infinitivos (batir, colocar), el presente con valor impersonal (bates, colocas), la estructura impersonal 'se + presente de indicativo' (se baten los huevos, se engrasa el molde) y el Imperativo de tú/usted (bate / bata).\n- Léxico: Utensilios de cocina (cuenco, tenedor, colador, fuente), ingredientes de pastelería, adverbios de cantidad e intensidad (un poco, bastante, sumamente, riquísimo).\n- Cultura y Sociedad: Costumbres culinarias de la merienda en Argentina e intercambios de recetas tradicionales.",
      inputs: "- Receta ilustrada real del Tiramisú (con listas de ingredientes de 250g de mascarpone, bizcochos, café exprés, cacao en polvo, etc.) y descripción de cada una de las fases de elaboración.\n- Video tutorial breve de cocina (DULCE DE TRES LECHES) con transcripción y actividades de rellenado.\n- Infografía del Arroz con Leche con instrucciones desordenadas.",
      enablingTasks: "Paso 1: Lluvia de ideas inicial sobre postres favoritos de los alumnos y toma de conciencia de qué vocabulario/verbos les falta en español para describirlos.\nPaso 2: Comprensión lectora de la receta del Tiramisú para identificar ingredientes, medidas, recipientes y vocabulario de verbos habituales.\nPaso 3: Foco macro-estructural de la receta de tres leches y arroz con leche: Identificar las partes fijas del texto (Título, ingredientes, fases numeradas).\nPaso 4: Foco gramatical e inducción: Comparación sobre cómo dar instrucciones en recetas (infinitivos vs. imperativos vs. 'se + presente'). Los alumnos reescriben los pasos usando 'se + 3ª persona'.\nPaso 5: '¡Jugamos a Cocineros!': Dinámica interactiva grupal en la que un estudiante actúa como chef mayor y da directivas en imperativo a los compañeros, quienes deben mimar el gesto de la acción culinaria solicitada.",
      finalTask: "La secuencia concluye con una doble tarea final: 1) Escribir individualmente de forma pulida la receta de su postre favorito detallando fases, ingredientes y dificultad de preparación para confeccionar cooperativamente el 'Libro de Recetas de la Clase'. 2) Llevar a cabo una sesión de simulación/degustación en la que valoran y prueban los postres con expresiones como '¡Está riquísimo!', 'Está en su punto' o 'Lleva mucho tiempo'."
    }
  },
  {
    label: "Ejemplo 3: El Cine de Almodóvar (Nivel 4 / Pre-Intermedio 2)",
    sequence: {
      title: "Elaboramos un álbum de biografías y críticas de cartelera",
      targetLevel: "Nivel 4 (Pre-Intermedio 2)",
      targetGroupDescription: "Estudiantes de nivel intermedio (B1), interesados en aspectos estéticos, culturales y artísticos de España y Latinoamérica. Requieren expandir sus habilidades de argumentación y uso del pasado.",
      objectives: "Que los estudiantes sean capaces de:\n1. Narrar acontecimientos del pasado alternando adecuadamente Pretérito Indefinido, Imperfecto y Pluscuamperfecto.\n2. Sintetizar argumentos complicados redactando sinopsis concisas de películas.\n3. Expresar intenciones artísticas, opiniones y preferencias justificadas con argumentos simples.\n4. Identificar figuras y referencias culturales claves del cine hispanohablante.",
      contents: "- Gramática: Alternancia de los tiempos del pasado (Indefinido, Imperfecto, Pluscuamperfecto). Contraste entre Pretérito Indefinido y Pretérito Perfecto. Usos de comparativos matizados ('lo que más me gusta es...').\n- Léxico: Géneros cinematográficos, adjetivos descriptivos de carácter y personalidad, vocabulario de la industria artística (director, reparto, sinopsis, banda sonora).\n- Cultura: Biografía de Pedro Almodóvar, canciones iconográficas de su B.S.O. ('Cucurrucucú Paloma' por Caetano Veloso) y la Movida Madrileña.",
      inputs: "- Texto biográfico descriptivo de Pedro Almodóvar con sus años de trabajo en Telefónica e influencia underground.\n- Transcripción de la canción de Sabina 'Yo quiero ser una chica Almodóvar' que contiene múltiples títulos de películas.\n- Cuatro sinopsis resumidas de films selectos (La mala educación, Átame, Matador, Laberinto de pasiones).",
      enablingTasks: "Paso 1: Motivación: Diálogos guiados acerca del cine español y directores conocidos. Visionado de un clip sin sonido de 2 minutos de 'Mujeres al borde de un ataque de nervios' para adivinar situaciones, diálogos de los personajes y el tono dramático.\nPaso 2: Lectura y Foco Formal del Pasado: Análisis de la biografía de Almodóvar. Los alumnos extraen verbos en Pretérito Indefinido y los clasifican en regulares e irregulares (fui, hice, estuve, pude, tuve).\nPaso 3: Escritura colectiva: Re-escribir la biografía de Almodóvar en primera persona de manera cooperativa.\nPaso 4: Análisis léxico y de canciones: Escuchar la canción de Sabina, identificar las referencias de películas en cada estrofa y discutir expresiones coloquiales ('comer el coco', 'pasando de todo', 'chungo', 'apuntarse a un bombardeo').",
      finalTask: "Los estudiantes se organizarán en pequeños grupos para elegir una película clave de Pedro Almodóvar, visionarla o investigar sobre ella, redactar una ficha técnica detallada y una sinopsis sintetizada colectivamente (entre 60 y 70 palabras). Como producto final, integrarán todas las fichas grupales junto a las biografías individuales en un 'Álbum Colectivo de Cine de la Clase' o blog digital, el cual será expuesto y defendido oralmente, justificando los motivos de elección."
    }
  }
];
